name: Create FINOS Waltz release branch

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'The release to create a branch for'
        type: string
        required: true

jobs:
  create-branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - id: release-short
        run: |
          # Use . as a delimiter, and get only the major and minor versions (first 2 fields).
          short_version=$(echo ${{ github.event.inputs.release }} | cut -d. -f1-2)
          echo "::set-output name=short_version::$short_version"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install charmcraft --classic

      - name: Update bundle.yaml
        run: |
          # Create an overlay yaml file with the desired release version for FINOS Waltz,
          # and apply it over the bundle.yaml file.
          echo "applications:" > overlay.yaml
          echo "  finos-waltz:" >> overlay.yaml
          echo "    channel: ${{ steps.release-short.outputs.short_version }}/edge" >> overlay.yaml

          # We can't have bundle.yaml as both the source and destionation, the result will not be
          # as we would have wanted it.
          cp bundle.yaml bundle2.yaml
          yq eval-all '. as $item ireduce ({}; . *+ $item)' bundle2.yaml overlay.yaml > bundle.yaml

          cat bundle.yaml

      - name: Create branch and commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'bundle.yaml'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Claudiu Belu

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: cbelu@cloudbasesolutions.com

          # Additional arguments for the git commit command. The --message argument is already set by the message i              nput.
          # Default: ''
          commit: --signoff

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "Creates ${{ github.event.inputs.release }} release"

          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
          new_branch: "release-${{ github.event.inputs.release }}"

      - name: Upload bundle to edge
        # TODO: replace with  canonical/charming-actions/upload-bundle once the following issue
        # is resolved: https://github.com/canonical/charming-actions/issues/40
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMHUB_TOKEN }}"
        run: |
          charmcraft pack
          charmcraft upload finos-waltz-bundle.zip
          # Get the last revision number and image revision number and release.
          bundle_rev=$(charmcraft revisions finos-waltz-bundle | awk 'FNR == 2 {print $1}')
          charmcraft release finos-waltz-bundle --revision=${bundle_rev} --channel="${{ steps.release-short.outputs.short_version }}/edge"
